- hosts: localhost
  tasks:
    - name: Install Python dependencies
      pip:
        name:
          - google-cloud-language
          - google-cloud-bigquery

    - name: Run yt comments ingestion job
      command: python3 ../../app/main.py